#!/usr/bin/bash
set -o pipefail

switch_to() {
    if [[ -z $TMUX ]]; then
        tmux attach-session -t "$1"
    else
        tmux switch-client -t "$1"
    fi
}

# List up the sessions
sessions=$(tmux list-sessions -F "#{session_name}" 2>/dev/null)

# Prompt for selection
selected=$(echo "$sessions" | fzf --tmux=center,100% --prompt="Select or create session: " --print-query)

query=$(echo "$selected" | head -n1)
match=$(echo "$selected" | tail -n1)

session_name=${match:-$query}

[ -z "$session_name" ] && exit 0

# Attach or create the new session
if ! tmux has-session -t "$session_name" 2>/dev/null; then
  tmux new -d -s "$session_name"
fi

switch_to "$session_name"
